name: Deploy Nuxt App

on:
  push:
    branches:
      - master  # ветка, по которой будет деплой

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 77.95.201.93
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/wedding
          git pull origin master
          npm install
          npm run build
          pm2 restart nuxt-app
